apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: derbyzoneOffers
  version: v1
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""